### ISSUE TITLE
THANK YOU FOR THIS

### ISSUE THREAD

**Issue by samelie** [ibsukru/mono-next#3]
ive tried every configuration under the sun with https://www.npmjs.com/package/tsconfig-paths and webpacks and madness
This is so clean

**Comment by ibsukru** [comment]
@samelie I am glad to hear that it solves your problem, keep in mind I am moving this sample to https://github.com/mutationapp/monolisa, Monalisa will aim to provide guidelines for similar challenges. It will be nurtured by mutation.app.

**Comment by samelie** [comment]
Awesome, will check it out
